import { createClient } from "@/lib/supabase/server";
import { formatSurvivalAdvice } from "@/lib/format-survival-advice";
import VoteButtons from "./VoteButtons";

export default async function FeedPage() {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  const { data: posts, error } = await supabase
    .from("survival_posts")
    .select(`
      id,
      situation,
      title,
      content,
      created_at,
      profiles (
        first_name,
        last_name,
        avatar_url
      ),
      votes (
        user_id,
        vote_value
      )
    `)
    .order("created_at", { ascending: false });

  if (error) {
    console.error("Feed error:", error);

    return (
      <main className="min-h-screen bg-[#e8f3fb] px-4 py-10 text-[#101c2a] sm:px-6">
        <div className="mx-auto max-w-2xl rounded-[28px] border border-[#174f82]/15 bg-white p-8 shadow-[0_18px_40px_rgba(16,47,77,0.1)]">
          <p className="text-[10px] font-black uppercase tracking-[0.2em] text-[#174f82]">Columbia Survival Guide</p>
          <p className="mt-4 text-lg text-[#33465a]">Failed to load posts.</p>
        </div>
      </main>
    );
  }

  return (
    <main className="min-h-screen bg-[#e8f3fb] text-[#101c2a]">
      <div className="mx-auto max-w-5xl px-4 py-10 sm:px-6 lg:px-8">
        <header className="mb-8 relative overflow-hidden rounded-[28px] bg-[#174f82] px-5 py-6 text-white shadow-[0_22px_50px_rgba(16,47,77,0.18)] sm:px-7">
          <div className="blueprint-dots absolute inset-0 opacity-30" />
          <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
            <div className="relative">
              <p className="text-[10px] font-black uppercase tracking-[0.22em] text-[#a9d5f8]">
                Columbia Survival Guide
              </p>
              <h1 className="mt-2 text-4xl font-black tracking-[-0.05em] text-white sm:text-5xl">
                Community feed
              </h1>
            </div>
            <p className="relative text-sm text-[#d8eafb]">
              Survival advice generated by Columbia students.
            </p>
          </div>
        </header>

        {!posts || posts.length === 0 ? (
          <div className="rounded-[28px] border border-[#174f82]/15 bg-white p-8 text-center shadow-[0_18px_40px_rgba(16,47,77,0.08)]">
            <h2 className="text-2xl font-bold text-[#101c2a]">No survival advice has been posted yet.</h2>
          </div>
        ) : (
          <div className="grid grid-cols-1 gap-8">
            {posts.map((post) => {
              const helpfulFunnyCount =
                post.votes?.filter((vote) => vote.vote_value === 1).length ?? 0;

              const doesntHitCount =
                post.votes?.filter((vote) => vote.vote_value === 0).length ?? 0;

              const currentUserVote =
                post.votes?.find((vote) => vote.user_id === user?.id)?.vote_value ?? null;

              return (
                <article
                  key={post.id}
                  className="editorial-card fade-up rounded-[28px] border border-[#174f82]/15 bg-white p-5 shadow-[0_18px_42px_rgba(16,47,77,0.09)] sm:p-6"
                >
                  <div className="mx-auto w-full max-w-3xl">
                  <p className="inline-flex -rotate-1 rounded-full bg-[#d6eafa] px-3 py-1 text-[10px] font-black uppercase tracking-[0.18em] text-[#174f82]">
                    Campus dispatch
                  </p>

                  <h2 className="mt-4 text-3xl font-black tracking-[-0.05em] text-[#101c2a] sm:text-4xl">
                    {post.title}
                  </h2>

                  <div className="mt-5 rounded-2xl border-l-4 border-[#75aadb] bg-[#edf6fc] p-4">
                    <p className="text-[11px] font-black uppercase tracking-[0.2em] text-[#174f82]">
                      The Crisis
                    </p>
                    <p className="mt-2 text-base leading-7 text-[#263f58]">
                      {post.situation}
                    </p>
                  </div>

                  <div className="mt-5">
                    <p className="text-[11px] font-black uppercase tracking-[0.2em] text-[#174f82]">
                      The Survival Advice
                    </p>
                    <p className="mt-3 whitespace-pre-line text-lg leading-8 text-[#17283a]">
                      {formatSurvivalAdvice(post.content)}
                    </p>
                  </div>

                  <VoteButtons
                    postId={post.id}
                    initialHelpfulFunny={helpfulFunnyCount}
                    initialDoesntHit={doesntHitCount}
                    initialUserVote={currentUserVote}
                  />
                  </div>
                </article>
              );
            })}
          </div>
        )}
      </div>
    </main>
  );
}
